config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get :root, to: 'welcome#index'

  resources :merchants do
    resources :items, only: [:index]
  end

  resources :items, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [:edit, :update, :destroy]

  get '/cart', to: 'cart#show'
  post '/cart/:item_id', to: 'cart#add_item'
  delete '/cart', to: 'cart#empty'
  patch '/cart/:change/:item_id', to: 'cart#update_quantity'
  delete '/cart/:item_id', to: 'cart#remove_item'

  resources :users, only: [:create, :update]
  get '/registration', to: 'users#new', as: :registration
  patch '/user/:id', to: 'users#update'
  get '/profile', to: 'users#show'
  get '/profile/edit', to: 'users#edit'
  get '/profile/edit_password', to: 'users#edit_password'
  post '/orders', to: 'user/orders#create'
  get '/profile/orders', to: 'user/orders#index'
  get '/profile/orders/:id', to: 'user/orders#show'
  delete '/profile/orders/:id', to: 'user/orders#cancel'
  get '/profile/orders/edit/:id', to: 'user/orders#edit'
  patch '/profile/orders/:id', to: 'user/orders#update'

  get 'profile/addresses/:id', to: 'addresses#edit', as: :edit_address
  delete 'profile/addresses/:id', to: 'addresses#destroy', as: :delete_address
  patch 'profile/addresses/:id', to: 'addresses#update'
  get 'profile/addresses', to: 'addresses#new'
  post 'profile/addresses', to: 'addresses#create', as: :add_address

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#login'
  get '/logout', to: 'sessions#logout'

  namespace :merchant do
    get '/', to: 'dashboard#index', as: :dashboard
    resources :orders, only: :show
    resources :items, only: [:index, :new, :create, :edit, :update, :destroy]
    put '/items/:id/change_status', to: 'items#change_status'
    get '/orders/:id/fulfill/:order_item_id', to: 'orders#fulfill'
  end

  namespace :admin do
    get '/', to: 'dashboard#index', as: :dashboard
    resources :merchants, only: [:show, :update]
    resources :users, only: [:index, :show]
    patch '/orders/:id/ship', to: 'orders#ship'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :merchant, optional: true
  has_many :orders
  has_many :addresses

  validates_presence_of :name,
                        :email

  validates_uniqueness_of :email

  enum role: ['default', 'merchant_admin', 'admin']
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/user/orders_controller.rb
class User::OrdersController < ApplicationController
  before_action :exclude_admin

  def index
    @orders = current_user.orders
  end

  def show
    @order = current_user.orders.find(params[:id])
  end

  def create
    address = Address.find(params[:address_id])
    order = current_user.orders.new(address_id: address.id)
    order.save
      cart.items.each do |item|
        order.order_items.create({
          item: item,
          quantity: cart.count_of(item.id),
          price: item.price
        })
      end
    session.delete(:cart)
    flash[:notice] = "Order created successfully!"
    redirect_to '/profile/orders'
  end

  def cancel
    order = current_user.orders.find(params[:id])
    order.cancel
    redirect_to "/profile/orders/#{order.id}"
  end

  def update
    order = current_user.orders.find(params[:id])
    order.update(address_params)  
    if order.save
      redirect_to "/profile/orders/#{order.id}"  
      flash[:notice] = "Shipping address updated successfully!"
    end 
  end

  def edit
    @order = current_user.orders.find(params[:id]) 
  end

  private
    def address_params
      params.permit(:address_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: :show
  before_action :exclude_admin, only: :show

  def show
    @user = User.find(current_user.id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(
      name: params[:name], 
      email: params[:email], 
      password: params[:password]
    )
    if @user.save
      @address = @user.addresses.create(
        address: params[:street_address], 
        city: params[:city], 
        state: params[:state], 
        zip: params[:zip], 
        nickname: "home"
      )
      if @address.save
        session[:user_id] = @user.id
        flash[:notice] = "Welcome, #{@user.name}!"
        redirect_to profile_path
      else
        generate_flash(@address)
        render :new
      end
    else
      generate_flash(@user)
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def edit_password
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = 'Profile has been updated!'
      redirect_to profile_path
    else
      generate_flash(@user)
      render :edit
    end
  end

  private 
    def user_params
      params.permit(:name, :password, :email, :password_confirmation, :city, :state, :zip, :street_address)
    end
end

app/views/users/_address.html.erb
<section id="address-<%= address.id %>">
  <h2><%= address.nickname %></h2>
  <p><%= address.address %></p>
  <p><%= address.city %>, <%= address.state %> <%= address.zip %></p>
  <%= button_to "Edit", edit_address_path(address), method: :get %>
  <%= button_to "Delete", delete_address_path(address), method: :delete if !address.has_orders? %>
</section>

app/views/users/edit.html.erb
<h1>Update Profile</h1>

<%= form_tag user_path(@user), method: :patch do %>
  <%= label_tag "Name" %>
  <%= text_field_tag :name %>

  <%= label_tag "Email" %>
  <%= email_field_tag :email %>

  <%= submit_tag "Update Profile" %>
<% end %>

app/views/users/edit_password.html.erb
<h1>Update Password</h1>

<%= form_tag user_path(@user), method: :patch do %>
  <%= label_tag :password %>
  <%= text_field_tag :password %>

  <%= label_tag :password_confirmation %>
  <%= text_field_tag :password_confirmation %>

  <%= submit_tag "Change Password" %>
<% end %>

app/views/users/new.html.erb
<h1>Create Account</h1>

<%= form_tag "/users" do %>
  <%= label_tag "Name" %>
  <%= text_field_tag :name %>

  <%= label_tag "Street Address" %>
  <%= text_field_tag :street_address %>

  <%= label_tag "City" %>
  <%= text_field_tag :city %>

  <%= label_tag "State" %>
  <%= text_field_tag :state %>

  <%= label_tag "Zip" %>
  <%= text_field_tag :zip %>

  <%= label_tag "Email" %>
  <%= email_field_tag :email %>

  <%= label_tag "Password" %>
  <%= password_field_tag :password %>

  <%= label_tag "Confirm Password" %>
  <%= password_field_tag :password_confirmation %>
  
  <%= submit_tag "Register" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p><%= @user.email %></p>
<%= link_to 'Edit', '/profile/edit' %>
<%= link_to 'Change Password', '/profile/edit_password' %>
<%= link_to 'My Orders', '/profile/orders' %>
<%= link_to 'Add new address', '/profile/addresses' %>


<%  @user.addresses.each do |address| %>
  <%= render partial: 'address', locals: { address: address, user: @user } %>
<% end %>