config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get :root, to: 'welcome#index'

  resources :merchants do
    resources :items, only: [:index]
  end

  resources :items, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [:edit, :update, :destroy]

  get '/cart', to: 'cart#show'
  post '/cart/:item_id', to: 'cart#add_item'
  delete '/cart', to: 'cart#empty'
  patch '/cart/:change/:item_id', to: 'cart#update_quantity'
  delete '/cart/:item_id', to: 'cart#remove_item'

  resources :users, only: [:create, :update]
  get '/registration', to: 'users#new', as: :registration
  patch '/user/:id', to: 'users#update'
  get '/profile', to: 'users#show'
  get '/profile/edit', to: 'users#edit'
  get '/profile/edit_password', to: 'users#edit_password'
  post '/orders', to: 'user/orders#create'
  get '/profile/orders', to: 'user/orders#index'
  get '/profile/orders/:id', to: 'user/orders#show'
  delete '/profile/orders/:id', to: 'user/orders#cancel'
  get '/profile/orders/edit/:id', to: 'user/orders#edit'
  patch '/profile/orders/:id', to: 'user/orders#update'

  get 'profile/addresses/:id', to: 'addresses#edit', as: :edit_address
  delete 'profile/addresses/:id', to: 'addresses#destroy', as: :delete_address
  patch 'profile/addresses/:id', to: 'addresses#update'
  get 'profile/addresses', to: 'addresses#new'
  post 'profile/addresses', to: 'addresses#create', as: :add_address

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#login'
  get '/logout', to: 'sessions#logout'

  namespace :merchant do
    get '/', to: 'dashboard#index', as: :dashboard
    resources :orders, only: :show
    resources :items, only: [:index, :new, :create, :edit, :update, :destroy]
    put '/items/:id/change_status', to: 'items#change_status'
    get '/orders/:id/fulfill/:order_item_id', to: 'orders#fulfill'
  end

  namespace :admin do
    get '/', to: 'dashboard#index', as: :dashboard
    resources :merchants, only: [:show, :update]
    resources :users, only: [:index, :show]
    patch '/orders/:id/ship', to: 'orders#ship'
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :merchant
  has_many :order_items
  has_many :orders, through: :order_items
  has_many :reviews, dependent: :destroy

  validates_presence_of :name,
                        :description,
                        :image,
                        :price,
                        :inventory

  def self.active_items
    where(active: true)
  end

  def self.by_popularity(limit = nil, order = "DESC")
    left_joins(:order_items)
    .select('items.id, items.name, COALESCE(sum(order_items.quantity), 0) AS total_sold')
    .group(:id)
    .order("total_sold #{order}")
    .limit(limit)
  end

  def sorted_reviews(limit = nil, order = :asc)
    reviews.order(rating: order).limit(limit)
  end

  def average_rating
    reviews.average(:rating)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    if params[:merchant_id]
      @merchant = Merchant.find(params[:merchant_id])
      @items = @merchant.items
    else
      @items = Item.active_items
    end
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/controllers/merchant/items_controller.rb
class Merchant::ItemsController < Merchant::BaseController
  def index
    @items = current_user.merchant.items
  end

  def new
  end

  def create
    merchant = current_user.merchant
    item = merchant.items.new(item_params)
    if item.save
      redirect_to "/merchant/items"
    else
      generate_flash(item)
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to "/merchant/items"
    else
      generate_flash(@item)
      render :edit
    end
  end

  def change_status
    item = Item.find(params[:id])
    item.update(active: !item.active)
    if item.active?
      flash[:notice] = "#{item.name} is now available for sale"
    else
      flash[:notice] = "#{item.name} is no longer for sale"
    end
    redirect_to '/merchant/items'
  end

  def destroy
    item = Item.find(params[:id])
    if item.orders.empty?
      item.destroy
    else
      flash[:notice] = "#{item.name} can not be deleted - it has been ordered!"
    end
    redirect_to '/merchant/items'
  end

  private

  def item_params
    params.permit(:name, :description, :price, :image, :inventory)
  end
end

app/views/items/_index.html.erb
<section class='statistics'>
  <h3>Most Popular Items:</h3>
  <% @items.by_popularity(5, "DESC").each do |item| %>
    <li><%= item.name %>: <%= item.total_sold %> sold</li>
  <% end %>
  <h3>Least Popular Items:</h3>
  <% @items.by_popularity(5, "ASC").each do |item| %>
    <li><%= item.name %>: <%= item.total_sold %> sold</li>
  <% end %>
</section>

<% @items.each do |item| %>
  <section id='item-<%= item.id%>'>
    <h2><%= link_to item.name, "/items/#{item.id}" %></h2>
    <p><%= item.description %></p>
    <%= link_to(image_tag(item.image), item_path(item), id: 'image') %>
    <p>Price: <%= number_to_currency(item.price) %></p>
    <p>Sold by: <%= link_to item.merchant.name, "/merchants/#{item.merchant_id}" %>, Inventory: <%= item.inventory %></p>
    <p><%= item.active ? "Active" : "Inactive" %></p>
    <% if current_merchant_user? %>
      <% if item.active? %>
        <%= button_to 'Inactivate', "/merchant/items/#{item.id}/change_status", method: :put %>
      <% elsif !item.active? %>
        <%= button_to 'Activate', "/merchant/items/#{item.id}/change_status", method: :put %>
      <% end %>
      <%= link_to 'Update Item', "/merchant/items/#{item.id}/edit" %>
      <%= button_to 'Delete', "/merchant/items/#{item.id}", method: :delete if item.orders.empty? %>
    <% end %>
  </section>
<% end %>

app/views/items/index.html.erb
<% if @merchant %>
  <h1>All Items From <%= link_to @merchant.name, "/merchant/#{@merchant.id}" %></h1>
<% else %>
  <h1>All Items</h1>
<% end %>

<%= render 'index' %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<p><%= @item.description %></p>
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaLM_vbg2Rh-mZ-B4t-RSU9AmSfEEq_SN9xPP_qrA2I6Ftq_D9Qw">
<p>Price: <%= number_to_currency(@item.price) %></p>
<p>Sold by: <%= link_to @item.merchant.name, "/merchants/#{@item.merchant_id}" %>, Inventory: <%= @item.inventory %></p>
<p><%= @item.active ? "Active" : "Inactive" %></p>

<%= button_to 'Add to Cart', "/cart/#{@item.id}" %>

<section class='reviews'>
  <h2>Reviews</h2>
  <% if @item.reviews.empty? %>
    <p>No Reviews Yet!</p>
  <% else %>
    <h3>Average Rating: <%= @item.average_rating.round(2) %></h3>
    <section id='top-three-reviews'>
      <h3>Top 3 Reviews</h3>
      <ul>
        <% @item.sorted_reviews(3, :desc).each do |review| %>
          <li><%= review.title %></li>
        <% end %>
      </ul>
    </section>
    <section id='bottom-three-reviews'>
      <h3>Bottom 3 Reviews</h3>
      <ul>
        <% @item.sorted_reviews(3, :asc).each do |review| %>
          <li><%= review.title %></li>
        <% end %>
      </ul>
    </section>
    <% @item.reviews.each do |review| %>
      <section id='review-<%= review.id %>'>
        <h3><%= review.title %></h3>
        <p><%= review.description %></p>
        <p>Rating: <%= review.rating %></p>
        <%= button_to 'Edit', edit_review_path(review), method: :get %>
        <%= button_to 'Delete', review_path(review), method: :delete %>
      </section>
    <% end %>
  <% end %>
  <%= button_to 'Add Review', new_item_review_path(@item), method: :get %>
</section>